# 工作流名称
name: C++ CI/CD for Chatroom
# 触发条件：main分支有push/PR时执行
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 任务定义
jobs:
  # 任务1：编译+测试（Ubuntu环境）
  build-and-test:
    # 运行环境：这里是我本地自带的版本
    runs-on: ubuntu-24.04

    # 步骤
    steps:
      # 步骤1：拉取代码到GitHub服务器
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：准备环境安装编译器、构建工具以及 Google Test 框架
      - name: Install dependencies
        run: |
          sudo apt update
          # googletest 包含源码，libgtest-dev 包含静态库链接信息
          sudo apt install -y g++ cmake libgtest-dev googletest

      # 步骤3：创建build目录并编译
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake -DBUILD_TESTS=ON ..
          make -j$(nproc)

      # 步骤4：运行所有单元测试
      - name: Run unit tests
        run: |
          cd build
          # 使用 ctest 自动发现并运行所有在 CMakeLists 中注册过的测试
          # --output-on-failure 会在测试失败时显示具体的 C++ 报错信息
          ctest --output-on-failure